#############################################################################
# Makefile for building: echoclient
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  echo_client.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile echo_client.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = echoclient1.0.0
DISTDIR = /var/www/html/projet_cir2/echo_client/.tmp/echoclient1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/lib/ -lmysqlcppconn -L/var/www/html/projet_cir2/echo_client/SmtpClient/src/SmtpMime -lQt5WebSockets -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		echoclient.cpp \
		database.cpp \
		SmtpClient/src/smtpclient.cpp \
		SmtpClient/src/mimetext.cpp \
		SmtpClient/src/mimepart.cpp \
		SmtpClient/src/mimemessage.cpp \
		SmtpClient/src/emailaddress.cpp \
		SmtpClient/src/mimeattachment.cpp \
		SmtpClient/src/mimebase64encoder.cpp \
		SmtpClient/src/mimebase64formatter.cpp \
		SmtpClient/src/mimebytearrayattachment.cpp \
		SmtpClient/src/mimecontentencoder.cpp \
		SmtpClient/src/mimecontentformatter.cpp \
		SmtpClient/src/mimefile.cpp \
		SmtpClient/src/mimehtml.cpp \
		SmtpClient/src/mimeinlinefile.cpp \
		SmtpClient/src/mimemultipart.cpp \
		SmtpClient/src/mimeqpencoder.cpp \
		SmtpClient/src/mimeqpformatter.cpp \
		SmtpClient/src/quotedprintable.cpp moc_echoclient.cpp \
		moc_smtpclient.cpp \
		moc_mimecontentformatter.cpp
OBJECTS       = main.o \
		echoclient.o \
		database.o \
		smtpclient.o \
		mimetext.o \
		mimepart.o \
		mimemessage.o \
		emailaddress.o \
		mimeattachment.o \
		mimebase64encoder.o \
		mimebase64formatter.o \
		mimebytearrayattachment.o \
		mimecontentencoder.o \
		mimecontentformatter.o \
		mimefile.o \
		mimehtml.o \
		mimeinlinefile.o \
		mimemultipart.o \
		mimeqpencoder.o \
		mimeqpformatter.o \
		quotedprintable.o \
		moc_echoclient.o \
		moc_smtpclient.o \
		moc_mimecontentformatter.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		echo_client.pro echoclient.h \
		database.h \
		SmtpClient/src/smtpclient.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimeattachment.h \
		SmtpClient/src/mimebase64encoder.h \
		SmtpClient/src/mimebase64formatter.h \
		SmtpClient/src/mimebytearrayattachment.h \
		SmtpClient/src/mimecontentencoder.h \
		SmtpClient/src/mimecontentformatter.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimehtml.h \
		SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/mimeqpencoder.h \
		SmtpClient/src/mimeqpformatter.h \
		SmtpClient/src/quotedprintable.h main.cpp \
		echoclient.cpp \
		database.cpp \
		SmtpClient/src/smtpclient.cpp \
		SmtpClient/src/mimetext.cpp \
		SmtpClient/src/mimepart.cpp \
		SmtpClient/src/mimemessage.cpp \
		SmtpClient/src/emailaddress.cpp \
		SmtpClient/src/mimeattachment.cpp \
		SmtpClient/src/mimebase64encoder.cpp \
		SmtpClient/src/mimebase64formatter.cpp \
		SmtpClient/src/mimebytearrayattachment.cpp \
		SmtpClient/src/mimecontentencoder.cpp \
		SmtpClient/src/mimecontentformatter.cpp \
		SmtpClient/src/mimefile.cpp \
		SmtpClient/src/mimehtml.cpp \
		SmtpClient/src/mimeinlinefile.cpp \
		SmtpClient/src/mimemultipart.cpp \
		SmtpClient/src/mimeqpencoder.cpp \
		SmtpClient/src/mimeqpformatter.cpp \
		SmtpClient/src/quotedprintable.cpp
QMAKE_TARGET  = echoclient
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = echoclient


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: echo_client.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		echo_client.pro \
		/usr/lib/x86_64-linux-gnu/libQt5WebSockets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile echo_client.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
echo_client.pro:
/usr/lib/x86_64-linux-gnu/libQt5WebSockets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile echo_client.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents echoclient.h database.h SmtpClient/src/smtpclient.h SmtpClient/src/mimetext.h SmtpClient/src/mimepart.h SmtpClient/src/mimemessage.h SmtpClient/src/emailaddress.h SmtpClient/src/smtpmime_global.h SmtpClient/src/mimeattachment.h SmtpClient/src/mimebase64encoder.h SmtpClient/src/mimebase64formatter.h SmtpClient/src/mimebytearrayattachment.h SmtpClient/src/mimecontentencoder.h SmtpClient/src/mimecontentformatter.h SmtpClient/src/mimefile.h SmtpClient/src/mimehtml.h SmtpClient/src/mimeinlinefile.h SmtpClient/src/mimemultipart.h SmtpClient/src/mimeqpencoder.h SmtpClient/src/mimeqpformatter.h SmtpClient/src/quotedprintable.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp echoclient.cpp database.cpp SmtpClient/src/smtpclient.cpp SmtpClient/src/mimetext.cpp SmtpClient/src/mimepart.cpp SmtpClient/src/mimemessage.cpp SmtpClient/src/emailaddress.cpp SmtpClient/src/mimeattachment.cpp SmtpClient/src/mimebase64encoder.cpp SmtpClient/src/mimebase64formatter.cpp SmtpClient/src/mimebytearrayattachment.cpp SmtpClient/src/mimecontentencoder.cpp SmtpClient/src/mimecontentformatter.cpp SmtpClient/src/mimefile.cpp SmtpClient/src/mimehtml.cpp SmtpClient/src/mimeinlinefile.cpp SmtpClient/src/mimemultipart.cpp SmtpClient/src/mimeqpencoder.cpp SmtpClient/src/mimeqpformatter.cpp SmtpClient/src/quotedprintable.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_echoclient.cpp moc_smtpclient.cpp moc_mimecontentformatter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_echoclient.cpp moc_smtpclient.cpp moc_mimecontentformatter.cpp
moc_echoclient.cpp: database.h \
		mysql_connection.h \
		cppconn/connection.h \
		cppconn/build_config.h \
		cppconn/warning.h \
		cppconn/sqlstring.h \
		cppconn/variant.h \
		cppconn/exception.h \
		cppconn/driver.h \
		cppconn/resultset.h \
		cppconn/config.h \
		cppconn/resultset_metadata.h \
		cppconn/datatype.h \
		cppconn/statement.h \
		cppconn/prepared_statement.h \
		echoclient.h \
		SmtpClient/src/SmtpMime \
		SmtpClient/src/smtpclient.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/mimehtml.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimeattachment.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/mimebytearrayattachment.h \
		echoclient.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/var/www/html/projet_cir2/echo_client -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include echoclient.h -o moc_echoclient.cpp

moc_smtpclient.cpp: SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/smtpclient.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/var/www/html/projet_cir2/echo_client -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SmtpClient/src/smtpclient.h -o moc_smtpclient.cpp

moc_mimecontentformatter.cpp: SmtpClient/src/mimecontentformatter.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/var/www/html/projet_cir2/echo_client -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/var/www/html/projet_cir2/echo_client/mysql-connector-cpp/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SmtpClient/src/mimecontentformatter.h -o moc_mimecontentformatter.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp echoclient.h \
		database.h \
		mysql_connection.h \
		cppconn/connection.h \
		cppconn/build_config.h \
		cppconn/warning.h \
		cppconn/sqlstring.h \
		cppconn/variant.h \
		cppconn/exception.h \
		cppconn/driver.h \
		cppconn/resultset.h \
		cppconn/config.h \
		cppconn/resultset_metadata.h \
		cppconn/datatype.h \
		cppconn/statement.h \
		cppconn/prepared_statement.h \
		SmtpClient/src/SmtpMime \
		SmtpClient/src/smtpclient.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/mimehtml.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimeattachment.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/mimebytearrayattachment.h \
		conversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

echoclient.o: echoclient.cpp echoclient.h \
		database.h \
		mysql_connection.h \
		cppconn/connection.h \
		cppconn/build_config.h \
		cppconn/warning.h \
		cppconn/sqlstring.h \
		cppconn/variant.h \
		cppconn/exception.h \
		cppconn/driver.h \
		cppconn/resultset.h \
		cppconn/config.h \
		cppconn/resultset_metadata.h \
		cppconn/datatype.h \
		cppconn/statement.h \
		cppconn/prepared_statement.h \
		SmtpClient/src/SmtpMime \
		SmtpClient/src/smtpclient.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/mimehtml.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimeattachment.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/mimebytearrayattachment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o echoclient.o echoclient.cpp

database.o: database.cpp database.h \
		mysql_connection.h \
		cppconn/connection.h \
		cppconn/build_config.h \
		cppconn/warning.h \
		cppconn/sqlstring.h \
		cppconn/variant.h \
		cppconn/exception.h \
		cppconn/driver.h \
		cppconn/resultset.h \
		cppconn/config.h \
		cppconn/resultset_metadata.h \
		cppconn/datatype.h \
		cppconn/statement.h \
		cppconn/prepared_statement.h \
		echoclient.h \
		SmtpClient/src/SmtpMime \
		SmtpClient/src/smtpclient.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/mimehtml.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimeattachment.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/mimebytearrayattachment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

smtpclient.o: SmtpClient/src/smtpclient.cpp SmtpClient/src/smtpclient.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimemessage.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smtpclient.o SmtpClient/src/smtpclient.cpp

mimetext.o: SmtpClient/src/mimetext.cpp SmtpClient/src/mimetext.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimetext.o SmtpClient/src/mimetext.cpp

mimepart.o: SmtpClient/src/mimepart.cpp SmtpClient/src/mimepart.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/quotedprintable.h \
		SmtpClient/src/mimebase64formatter.h \
		SmtpClient/src/mimecontentformatter.h \
		SmtpClient/src/mimeqpformatter.h \
		SmtpClient/src/mimebase64encoder.h \
		SmtpClient/src/mimecontentencoder.h \
		SmtpClient/src/mimeqpencoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimepart.o SmtpClient/src/mimepart.cpp

mimemessage.o: SmtpClient/src/mimemessage.cpp SmtpClient/src/mimemessage.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimemultipart.h \
		SmtpClient/src/emailaddress.h \
		SmtpClient/src/quotedprintable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimemessage.o SmtpClient/src/mimemessage.cpp

emailaddress.o: SmtpClient/src/emailaddress.cpp SmtpClient/src/emailaddress.h \
		SmtpClient/src/smtpmime_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emailaddress.o SmtpClient/src/emailaddress.cpp

mimeattachment.o: SmtpClient/src/mimeattachment.cpp SmtpClient/src/mimeattachment.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/mimefile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimeattachment.o SmtpClient/src/mimeattachment.cpp

mimebase64encoder.o: SmtpClient/src/mimebase64encoder.cpp SmtpClient/src/mimebase64encoder.h \
		SmtpClient/src/mimecontentencoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimebase64encoder.o SmtpClient/src/mimebase64encoder.cpp

mimebase64formatter.o: SmtpClient/src/mimebase64formatter.cpp SmtpClient/src/mimebase64formatter.h \
		SmtpClient/src/mimecontentformatter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimebase64formatter.o SmtpClient/src/mimebase64formatter.cpp

mimebytearrayattachment.o: SmtpClient/src/mimebytearrayattachment.cpp SmtpClient/src/mimebytearrayattachment.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimebytearrayattachment.o SmtpClient/src/mimebytearrayattachment.cpp

mimecontentencoder.o: SmtpClient/src/mimecontentencoder.cpp SmtpClient/src/mimecontentencoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimecontentencoder.o SmtpClient/src/mimecontentencoder.cpp

mimecontentformatter.o: SmtpClient/src/mimecontentformatter.cpp SmtpClient/src/mimecontentformatter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimecontentformatter.o SmtpClient/src/mimecontentformatter.cpp

mimefile.o: SmtpClient/src/mimefile.cpp SmtpClient/src/mimefile.h \
		SmtpClient/src/mimepart.h \
		SmtpClient/src/smtpmime_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimefile.o SmtpClient/src/mimefile.cpp

mimehtml.o: SmtpClient/src/mimehtml.cpp SmtpClient/src/mimehtml.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimetext.h \
		SmtpClient/src/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimehtml.o SmtpClient/src/mimehtml.cpp

mimeinlinefile.o: SmtpClient/src/mimeinlinefile.cpp SmtpClient/src/mimeinlinefile.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimefile.h \
		SmtpClient/src/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimeinlinefile.o SmtpClient/src/mimeinlinefile.cpp

mimemultipart.o: SmtpClient/src/mimemultipart.cpp SmtpClient/src/mimemultipart.h \
		SmtpClient/src/smtpmime_global.h \
		SmtpClient/src/mimepart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimemultipart.o SmtpClient/src/mimemultipart.cpp

mimeqpencoder.o: SmtpClient/src/mimeqpencoder.cpp SmtpClient/src/mimeqpencoder.h \
		SmtpClient/src/mimecontentencoder.h \
		SmtpClient/src/quotedprintable.h \
		SmtpClient/src/smtpmime_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimeqpencoder.o SmtpClient/src/mimeqpencoder.cpp

mimeqpformatter.o: SmtpClient/src/mimeqpformatter.cpp SmtpClient/src/mimeqpformatter.h \
		SmtpClient/src/mimecontentformatter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mimeqpformatter.o SmtpClient/src/mimeqpformatter.cpp

quotedprintable.o: SmtpClient/src/quotedprintable.cpp SmtpClient/src/quotedprintable.h \
		SmtpClient/src/smtpmime_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quotedprintable.o SmtpClient/src/quotedprintable.cpp

moc_echoclient.o: moc_echoclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_echoclient.o moc_echoclient.cpp

moc_smtpclient.o: moc_smtpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smtpclient.o moc_smtpclient.cpp

moc_mimecontentformatter.o: moc_mimecontentformatter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mimecontentformatter.o moc_mimecontentformatter.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient || mkdir -p $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/x86_64-linux-gnu/qt5/examples/websockets/echoclient/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

